name: build
on:
  workflow_dispatch
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bun Install
        run: bun i
      - name: Type Check
        run: bun tsc
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun -v
      - run: bun i
      - run: bun run build-win
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-for-win
          path: hippodamia-server.exe
        
    
